### ISSUE TITLE
An error occurred in the stream after a certain period of time.

### ISSUE THREAD

**Issue by jybaek** [jybaek/hanvi#2]
```bash
$ node hanvi.js
Listening, press Ctrl+C to stop.
{ Error: Exceeded maximum allowed stream duration of 65 seconds.
    at new ApiError (/Users/caley/work/hanvi/node_modules/@google-cloud/common/build/src/util.js:58:28)
    at DestroyableTransform.recognizeStream.setPipeline.through.obj [as _transform] (/Users/caley/work/hanvi/node_modules/@google-cloud/speech/src/helpers.js:108:18)
    at DestroyableTransform.Transform._read (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at StreamProxy.ondata (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at StreamProxy.emit (events.js:180:13)
    at addChunk (/Users/caley/work/hanvi/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  code: 11,
  errors: undefined,
  response: undefined,
  message: 'Exceeded maximum allowed stream duration of 65 seconds.' }
```

**Comment by jybaek** [comment]
First, if an error occurs, the program is terminated and managed by `pm2`.

```bash
$ pm2 start server.js --name "hanvi"
```

4899bb7333c4d9081589aafd7cff80e4815a8781
